add scalacheck-1-14 → scalacheck-1-15 migration
scala-steward-org/scala-steward pull request #1710
Opened 2020-11-03 07:56 UTC by larsrh

This is the first artifactId migration in the config file, so I'm not 100% sure this syntax is correct.

2020-11-03 15:37 UTC, mzuehlke requested changes

2020-11-03 15:37 UTC, mzuehlke commented on modules/core/src/main/resources/artifact-migrations.conf
> +    groupIdBefore = org.scalatestplus
```suggestion
    groupIdAfter = org.scalatestplus
```
It's the other way around: https://github.com/scala-steward-org/scala-steward/blob/master/docs/artifact-migrations.md
The `*After` fields are mandantory.

2020-11-03 16:25 UTC, mzuehlke approved these changes

2020-11-03 16:26 UTC, merged

2020-11-03 16:26 UTC, mzuehlke commented
thanks @larsrh

2020-11-09 13:42 UTC, larsrh commented
This does not appear to trigger, e.g. in Paiges: https://github.com/typelevel/paiges

2020-11-09 20:07 UTC, fthomas commented
Here is an excerpt from the log for Paiges:
```
2020-11-09 19:56:10,956 INFO  Ignore org.scalatestplus:(scalacheck-1-14, scalacheck-1-14_2.12) : 3.2.2.0 -> 3.3.0.0-SNAP2 (reason: no suitable next version)
2020-11-09 19:56:10,956 INFO  Ignore org.scalatestplus:(scalacheck-1-14, scalacheck-1-14_2.13) : 3.2.2.0 -> 3.3.0.0-SNAP2 (reason: no suitable next version)
2020-11-09 19:56:10,956 INFO  Ignore org.scalatestplus:(scalacheck-1-14, scalacheck-1-14_sjs1_2.12) : 3.2.2.0 -> 3.3.0.0-SNAP2 (reason: no suitable next version)
2020-11-09 19:56:10,956 INFO  Ignore org.scalatestplus:(scalacheck-1-14, scalacheck-1-14_sjs1_2.13) : 3.2.2.0 -> 3.3.0.0-SNAP2 (reason: no suitable next version)
```
The migration added here is not used because there are newer versions of that artifact available. Scala Steward currently only rewrites groupIds or artifactIds if there are no newer versions for the given artifact.

2020-11-10 08:36 UTC, larsrh commented
In that case, I think we're out of luck, since upstream will probably continue to release new versions.